#!/bin/bash

set -ex

DOTPATH=$HOME/.dotfiles

ln -snfv "$DOTPATH/.gemrc" "$HOME/.gemrc"
ln -snfv "$DOTPATH/.gitignore_global" "$HOME/.gitignore_global"
ln -snfv "$DOTPATH/.railsrc" "$HOME/.railsrc"
ln -snfv "$DOTPATH/.tmux" "$HOME/.tmux"
ln -snfv "$DOTPATH/.tmux.conf" "$HOME/.tmux.conf"
ln -snfv "$DOTPATH/.vim" "$HOME/.vim"
ln -snfv "$DOTPATH/.vimrc" "$HOME/.vimrc"
ln -snfv "$DOTPATH/.zsh" "$HOME/.zsh"
ln -snfv "$DOTPATH/.zshrc" "$HOME/.zshrc"
