[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
