[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'google/vim-jsonnet'
