call plug#begin($XDG_DATA_HOME . '/vim/plugged')

Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-sensible'

" fzf
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

" vim-lsp
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

call plug#end()

set clipboard=unnamed,unnamedplus
set completeopt=menuone,noinsert,noselect
set number

" netrw
let g:netrw_home = $XDG_DATA_HOME . '/vim'

function! s:LspConfig() abort
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> <leader>rn <plug>(lsp-rename)
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:LspConfig()
augroup END

set background=dark
color catppuccin
