set -g mouse on
set -g history-limit 30000
set -g set-clipboard on

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
